# Application Configuration

server:
  port: 8080
  host: 0.0.0.0

database:
  type: mysql
  host: localhost
  port: 3306
  username: user
  password: pass
  name: mydatabase

logging:
  level: info
  file: /var/log/application.log
